FROM mcr.microsoft.com/azurelinux/base/core:3.0

RUN tdnf update -y && \
    tdnf install ca-certificates-microsoft -y && \
    tdnf install golang -y

COPY . .
RUN go build -o bin/crypto-repro
CMD ["./bin/crypto-repro"]